* Value formatting discrepancy between browser and Rhino
  We run the SSF library on both the frontend (browser) and backend (Rhino context) for performing value formatting of results. Unfortunately it
  has been noticed that in some cases the values generated on the backend can differ from what is generated on the front end.

  Specifically in some cases the backend will happily generate a result while in the frontend an "Unsupported format" will be generated.

  After some searching/debugging, the discrepancy hinges on one clause where there are a couple of currency symbols being iterated over using
  `indexOf`, something that basically looks like this:

#+BEGIN_SRC javascript
    '$€'.indexOf(char) > -1
#+END_SRC

  For a given character, '€',  this will return -1 in Rhino, but find it successfully in the browser, resulting in the value 1.

  This project removes all the SSF complexity and creates one simple method that highlights the error, and a simple Rhino runner to test a few
  characters.

* Setup
1.  Install Ruby
2.  Make sure you have jruby setup

(I'll assume both of these are setup for the time. Please refer to other resources for this. )

3.  Install Jruby Rhino

#+BEGIN_SRC bash
jruby -S gem install therubyrhino`
 #+END_SRC

* Running this project

#+BEGIN_SRC bash
jruby test.rb
 #+END_SRC

* Running code in browsers
- Open a console in Chrome and open dev tools

#+BEGIN_SRC javascript
    var char = '$' // or '€'.  Both should return with a value greater than -1 (not found)
    var _symbols = '$€'
    _symbols.indexOf(char)
#+END_SRC
